language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - "node_modules"
install:
  - npm install
services: -mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    - npm run build
script:
  - npm run test
after_success:
  - npm run coverage
